/* Community OS: self-contained project dataset. No external organization data. */
const initiatives=[
{id:'learning',name:'לומדים ביחד',domain:'education',budget:12500,raised:14500,spent:11200,hours:180,participants:130},
{id:'youth',name:'מרחב לצמוח',domain:'education',budget:9500,raised:10200,spent:8800,hours:135,participants:95},
{id:'neighbors',name:'שכנים למען שכנים',domain:'support',budget:18000,raised:19500,spent:17700,hours:245,participants:175},
{id:'food',name:'שולחן משותף',domain:'support',budget:14000,raised:15200,spent:13600,hours:195,participants:210},
{id:'garden',name:'הגינה של כולנו',domain:'environment',budget:6500,raised:7100,spent:5800,hours:110,participants:65},
{id:'green',name:'שכונה ירוקה',domain:'environment',budget:5000,raised:5800,spent:4300,hours:85,participants:80}
];
const domainNames={education:'חינוך',support:'סיוע קהילתי',environment:'סביבה'};
const colors={education:'#7655e9',support:'#32c6a2',environment:'#f1b663'};
const months=['ינו׳','פבר׳','מרץ','אפר׳','מאי','יוני','יולי','אוג׳','ספט׳','אוק׳','נוב׳','דצמ׳'];
const seasonal=[.75,.82,.92,.86,1.02,1.12,1.05,.91,1.16,1.2,1.25,1.38];
const records=initiatives.flatMap((p,j)=>months.map((_,month)=>{const season=seasonal[month];return{id:p.id,month,domain:p.domain,budget:Math.round(p.budget*season),raised:Math.round(p.raised*season*(1+((month+j)%4-1.5)*.035)),spent:Math.round(p.spent*season*(1+((month*2+j)%5-2)*.03)),hours:Math.round(p.hours*season*(1+((month+j)%3-1)*.06)),participants:Math.round(p.participants*season*(1+((month+j)%4-1.5)*.05))}}));
const sum=(rs,key)=>rs.reduce((n,r)=>n+r[key],0),num=n=>Math.round(n).toLocaleString('he-IL'),money=n=>'₪'+num(n),pct=(a,b)=>b?Math.round(a/b*100):0;
function selection(period,domain){const start=period==='year'?0:(Number(period[1])-1)*3,end=period==='year'?12:start+3;return records.filter(r=>r.month>=start&&r.month<end&&(domain==='all'||r.domain===domain))}
const $=id=>document.getElementById(id);const svg=(w,h,content,label)=>`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${label}">${content}</svg>`;
function financeChart(rs,ms){const w=650,h=260,pad=55,bottom=225,ceiling=Math.ceil(Math.max(...ms.flatMap(m=>['raised','spent'].map(k=>sum(rs.filter(r=>r.month===m),k))))/20000)*20000||20000;const x=i=>pad+i*(w-pad-20)/Math.max(1,ms.length-1),y=n=>bottom-n/ceiling*180;let content='';for(let i=0;i<=3;i++){const v=ceiling*i/3;content+=`<line x1="${pad}" y1="${y(v)}" x2="${w-10}" y2="${y(v)}" stroke="#eeeaf5"/><text x="${pad-10}" y="${y(v)+5}" text-anchor="end">${Math.round(v/1000)}k</text>`}for(const [key,color] of [['raised','#7655e9'],['spent','#32c6a2']]){const vals=ms.map(m=>sum(rs.filter(r=>r.month===m),key));const points=vals.map((v,i)=>`${x(i)},${y(v)}`).join(' ');if(key==='raised')content+=`<polygon points="${x(0)},${bottom} ${points} ${x(ms.length-1)},${bottom}" fill="#7655e911"/>`;content+=`<polyline class="finance-path" points="${points}" fill="none" stroke="${color}" stroke-width="3" stroke-linejoin="round"/>`;vals.forEach((v,i)=>{content+=`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="white" stroke="${color}" stroke-width="2"><title>${months[ms[i]]} · ${key==='raised'?'גיוס':'הוצאה'}: ${money(v)}</title></circle>`})}ms.forEach((m,i)=>content+=`<text x="${x(i)}" y="252" text-anchor="middle">${months[m]}</text>`);return svg(w,h,content,'גיוס והוצאות לפי חודש; טבלת היוזמות מציגה את הסכומים לתקופה')}
function peopleChart(rs,ms,key){const w=650,h=225,pad=45,base=188,values=ms.map(m=>sum(rs.filter(r=>r.month===m),key)),max=Math.ceil(Math.max(...values)/500)*500||500,slot=(w-pad-10)/ms.length;let content='';for(let i=0;i<3;i++){const value=max*i/2,y=base-value/max*155;content+=`<line x1="${pad}" y1="${y}" x2="640" y2="${y}" stroke="#eeeaf5"/><text x="${pad-8}" y="${y+5}" text-anchor="end">${num(value)}</text>`}values.forEach((v,i)=>{const height=v/max*155,x=pad+i*slot+slot*.2;content+=`<rect x="${x}" y="${base-height}" width="${slot*.6}" height="${height}" rx="5" fill="${i===values.indexOf(Math.max(...values))?'#7655e9':'#dcd2fa'}"><title>${months[ms[i]]}: ${num(v)}</title></rect><text x="${x+slot*.3}" y="217" text-anchor="middle">${months[ms[i]]}</text>`});return svg(w,h,content,key==='hours'?'שעות התנדבות חודשיות':'מספר השתתפויות לפי חודש')}
function render(){const rs=selection($('period').value,$('domain').value),ms=[...new Set(rs.map(r=>r.month))].sort((a,b)=>a-b),funds=sum(rs,'raised'),spent=sum(rs,'spent'),budget=sum(rs,'budget'),hours=sum(rs,'hours'),people=sum(rs,'participants');$('selection-status').textContent=$('period').selectedOptions[0].textContent+' · '+$('domain').selectedOptions[0].textContent+' · '+new Set(rs.map(r=>r.id)).size+' יוזמות';$('kpi-funds').textContent=money(funds);$('kpi-people').textContent=num(people);$('kpi-hours').textContent=num(hours);$('kpi-budget').textContent=pct(spent,budget)+'%';$('funds-note').textContent='מול '+money(budget)+' בתכנון';$('hours-note').textContent=num(hours/ms.length)+' שעות בממוצע לחודש';$('budget-note').textContent=money(spent)+' הוצאה בפועל';$('balance').textContent=money(funds-spent);$('finance-chart').innerHTML=financeChart(rs,ms);$('people-chart').innerHTML=peopleChart(rs,ms,$('people-metric').value);$('spent-total').textContent=money(spent);let offset=0;const circumference=2*Math.PI*80;let rings='<circle cx="110" cy="110" r="80" fill="none" stroke="#f1eef7" stroke-width="20"/>';let legend='';for(const [key,name]of Object.entries(domainNames)){const amount=sum(rs.filter(r=>r.domain===key),'spent');if(!amount)continue;const part=amount/spent*circumference;rings+=`<circle cx="110" cy="110" r="80" fill="none" stroke="${colors[key]}" stroke-width="20" stroke-dasharray="${part} ${circumference-part}" stroke-dashoffset="${-offset}" transform="rotate(-90 110 110)"><title>${name}: ${money(amount)}</title></circle>`;offset+=part;legend+=`<div class="distribution-row"><i style="background:${colors[key]}"></i><span>${name}</span><strong>${money(amount)}</strong><small>${pct(amount,spent)}%</small></div>`}$('donut').innerHTML=svg(220,220,rings,'התפלגות הוצאות לפי תחום');$('distribution-legend').innerHTML=legend;const active=initiatives.filter(p=>rs.some(r=>r.id===p.id));const totals=active.map(p=>({...p,actualHours:sum(rs.filter(r=>r.id===p.id),'hours')}));const leader=totals.reduce((a,b)=>a.actualHours>b.actualHours?a:b);const peak=ms.reduce((a,b)=>sum(rs.filter(r=>r.month===a),'participants')>sum(rs.filter(r=>r.month===b),'participants')?a:b);$('insights').innerHTML=`<article class="insight"><span>01 / ENGAGEMENT</span><h3>${leader.name} מובילה בשעות התנדבות</h3><p>${num(leader.actualHours)} שעות — ${pct(leader.actualHours,hours)}% מכלל השעות בתקופה שנבחרה.</p></article><article class="insight"><span>02 / PARTICIPATION</span><h3>שיא ההשתתפות: ${months[peak]}</h3><p>${num(sum(rs.filter(r=>r.month===peak),'participants'))} השתתפויות בחודש, מתוך ${num(people)} בתקופה.</p></article><article class="insight"><span>03 / BUDGET</span><h3>${spent<=budget?'ההוצאה נמצאת במסגרת התכנון':'ההוצאה חורגת מהתכנון'}</h3><p>${money(Math.abs(budget-spent))} ${spent<=budget?'נותרו ביחס לתקציב המתוכנן':'מעל התקציב המתוכנן'}. יתרת הגיוס: ${money(funds-spent)}.</p></article>`;renderRows(rs)}
function renderRows(rs=selection($('period').value,$('domain').value)){const query=$('initiative-search').value.trim(),selected=initiatives.filter(p=>rs.some(r=>r.id===p.id)&&(p.name.includes(query)||domainNames[p.domain].includes(query)));$('initiative-rows').innerHTML=selected.map(p=>{const group=rs.filter(r=>r.id===p.id),spent=sum(group,'spent'),budget=sum(group,'budget'),ratio=pct(spent,budget);return`<tr><td><strong>${p.name}</strong><small>${domainNames[p.domain]}</small></td><td>${money(sum(group,'raised'))}</td><td>${money(spent)} / ${money(budget)}</td><td>${num(sum(group,'hours'))}</td><td>${num(sum(group,'participants'))}</td><td class="${ratio>100?'over-budget':''}"><span class="budget-meter"><span style="width:${Math.min(100,ratio)}%"></span></span>${ratio}%</td></tr>`}).join('');$('row-status').textContent=selected.length?selected.length+' יוזמות · החיפוש מסנן את הטבלה בלבד':'לא נמצאו יוזמות. נסו חיפוש אחר.'}
if(typeof document!=='undefined'){['period','domain','people-metric'].forEach(id=>$(id).addEventListener('change',render));$('initiative-search').addEventListener('input',()=>renderRows());render()}
if(typeof module!=='undefined')module.exports={records,selection,sum,initiatives};
